$(function () {
    'use strict';
    const api=dental.reports.reports,subscriptions=dental.reports.reportSubscription;
    const names={default:'Общий отчёт',day:'По дням',doctor:'По врачам',service:'По услугам',category:'По категориям',branch:'По филиалам',chair:'По креслам',heatmap:'День недели × час',supplier:'По поставщикам',month:'Динамика цен по месяцам',detail:'Детализация'};
    const days=['Воскресенье','Понедельник','Вторник','Среда','Четверг','Пятница','Суббота'];
    const storageKey='dental.reportFilters.'+abp.currentTenant.id+'.'+abp.currentUser.id;
    let catalog=[],detail=null,previous=null,generation=0;
    const error=e=>abp.message.error(e.message||e.responseJSON?.error?.message||'Не удалось выполнить действие.');
    const timezone=()=>abp.setting.get('Dental.Org.Timezone')||'Asia/Almaty';
    const iso=d=>d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');
    function input(){return {code:$('#ReportCode').val(),branchId:$('#ReportBranch').val()||null,doctorId:$('#ReportDoctor').val()||null,from:dentalCalendarDates.normalize($('#ReportFrom').val()),to:dentalCalendarDates.normalize($('#ReportTo').val()),inactiveMonths:Number($('#ReportMonths').val()),groupBy:detail?'detail':$('#ReportGrouping').val()||'default',detailKey:detail?.key||null,detailGroup:detail?.group||null};}
    function format(v,type){if(v==null)return '—';if(type==='DateTime')return new Date(v).toLocaleString('ru-RU',{timeZone:timezone()});if(type==='DateOnly')return String(v).split('-').reverse().join('.');if(['Decimal','Double','Int64','Int32'].includes(type))return Number(v).toLocaleString('ru-RU',{maximumFractionDigits:2});return String(v);}
    function resetDetail(){detail=null;$('#ReportBack').prop('hidden',true);}
    function heatmap(result){
        const chart=$('#ReportChart').empty(),table=$('<table class="table table-bordered text-center">'),head=$('<tr>').append('<th>День / час</th>'),hours=[...new Set(result.rows.map(r=>Number(r[1])))].sort((a,b)=>a-b);
        hours.forEach(h=>head.append($('<th scope="col">').text(String(h).padStart(2,'0')+':00')));table.append($('<thead>').append(head));const body=$('<tbody>');
        for(let day=1;day<=7;day++){const row=$('<tr>').append($('<th scope="row">').text(days[day%7]));hours.forEach(h=>{const cell=result.rows.find(r=>Number(r[0])===day&&Number(r[1])===h),value=cell?.[4],ratio=Math.min(1,Number(value||0)/100);row.append($('<td>').css({backgroundColor:value==null?'#f3f5f8':`rgba(85,73,255,${0.08+ratio*0.72})`,color:ratio>0.6?'#fff':'#18243a'}).attr('title',cell?`${format(cell[2],'Decimal')} мин занято / ${format(cell[3],'Decimal')} мин по графику`:'Нет рабочего времени').text(value==null?'—':format(value,'Decimal')+'%'));});body.append(row);}
        chart.append($('<h5>').text('Загрузка врачей по часам'),$('<div class="table-responsive">').append(table.append(body)));
    }
    function render(result,state){
        const table=$('<table class="table table-striped">'),head=$('<tr>'),body=$('<tbody>'),hasLinks=result.links.some(Boolean);
        result.columns.forEach(c=>head.append($('<th scope="col">').text(c.name)));if(hasLinks)head.append('<th>Открыть</th>');
        result.rows.forEach((row,i)=>{const tr=$('<tr>');row.forEach((v,n)=>{const cell=$('<td>').text(format(v,result.columns[n].type));
            if(n===0&&!detail&&state.groupBy!=='detail'&&result.drillKeys[i])cell.empty().append($('<button type="button" class="btn btn-link p-0 text-start">').text(format(v,result.columns[n].type)).on('click',()=>{previous=state;detail={key:result.drillKeys[i],group:previous.groupBy};$('#ReportBack').prop('hidden',false);load();}));
            if(state.code==='branches_comparison'&&n>0&&typeof v==='number'){const values=result.rows.map(r=>r[n]).filter(x=>typeof x==='number');if(values.length>1&&Math.min(...values)!==Math.max(...values)){const lower=result.columns[n].name.includes('Неявк')||result.columns[n].name.includes('Материалы'),best=lower?Math.min(...values):Math.max(...values),worst=lower?Math.max(...values):Math.min(...values);if(v===best)cell.addClass('table-success').attr('title','Лучшее значение');if(v===worst)cell.addClass('table-danger').attr('title','Худшее значение');}}
            tr.append(cell);});
            if(hasLinks){const cell=$('<td>'),link=result.links[i];if(link&&/^\/(Visits\/Detail|Patients\/Detail|Inventory\/Documents\/Edit|Schedule|Payroll|Cash)(\?|$)/.test(link))cell.append($('<a>').attr('href',link).text('Открыть'));tr.append(cell);}body.append(tr);});
        $('#ReportTable').empty().append(table.append($('<thead>').append(head),body));$('#ReportState').text(result.rows.length===0?'Нет данных за выбранный период.':result.rows.length+' строк'+(result.truncated?' · Показаны первые 5000. Сузьте фильтры.':''));
        const chart=$('#ReportChart').empty(),index=result.columns.findIndex((c,n)=>n>0&&['Decimal','Double','Int64','Int32'].includes(c.type));
        if(state.code==='utilization'&&state.groupBy==='heatmap')heatmap(result);
        else if(index>=0&&result.rows.length){const rows=result.rows.slice(0,20),max=Math.max(1,...rows.map(r=>Math.abs(Number(r[index]||0))));chart.append($('<h5>').text(result.columns[index].name));rows.forEach(r=>{const label=format(r[0],result.columns[0].type),value=Number(r[index]||0);chart.append($('<div class="d-flex gap-2 align-items-center mb-2">').append($('<span class="text-truncate">').css('width','160px').attr('title',label).text(label),$('<div class="flex-grow-1">').append($('<div>').css({height:'16px',width:Math.max(1,Math.abs(value)/max*100)+'%',background:value<0?'#dc3545':'#5549ff',borderRadius:'3px'})),$('<span>').text(format(value,result.columns[index].type))));});}
        ['Xlsx','Pdf','Csv'].forEach(f=>{const params=new URLSearchParams();Object.entries({...state,handler:'Export',format:f.toLowerCase()}).forEach(([k,v])=>{if(v!=null)params.set(k,v);});$('#Report'+f).attr('href','/Reports?'+params);});
    }
    async function load(){if(!$('#ReportCode').val())return;const query=input(),request=++generation,b=$('#ReportFilter button').prop('disabled',true);$('#ReportState').text('Формируем отчёт…');try{const result=await api.get(query);if(request===generation&&JSON.stringify(query)===JSON.stringify(input()))render(result,query);}catch(e){if(request===generation){$('#ReportState').text('Не удалось загрузить отчёт.');error(e);}}finally{if(request===generation)b.prop('disabled',false);}}
    function groups(selected='default'){$('#ReportGrouping').empty();(catalog.find(r=>r.code===$('#ReportCode').val())?.groupings||['default']).forEach(g=>$('#ReportGrouping').append($('<option>').val(g).text(names[g]||g)));$('#ReportGrouping').val(selected);}
    async function doctors(){const selected=$('#ReportDoctor').val();$('#ReportDoctor').empty().append('<option value="">Доступные врачи</option>');const rows=await dental.staff.employee.getLookup({branchId:$('#ReportBranch').val()||null});let items=rows.items;if(!abp.auth.isGranted('Dental.Schedule.ViewAll')&&!abp.auth.isGranted('Dental.Schedule.Manage')){const me=await dental.staff.employee.getCurrent();items=items.filter(d=>d.id===me.employeeId);}items.forEach(d=>$('#ReportDoctor').append($('<option>').val(d.id).text(d.fullName||d.name)));$('#ReportDoctor').val(items.some(d=>d.id===selected)?selected:'');}
    function preset(){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:timezone(),year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()),get=t=>parts.find(p=>p.type===t).value,now=new Date(Number(get('year')),Number(get('month'))-1,Number(get('day')),12),code=$('#ReportPreset').val();let from=now,to=now;if(code==='week'){from=new Date(now);from.setDate(now.getDate()-((now.getDay()+6)%7));}if(code==='month')from=new Date(now.getFullYear(),now.getMonth(),1);if(code==='previousMonth'){from=new Date(now.getFullYear(),now.getMonth()-1,1);to=new Date(now.getFullYear(),now.getMonth(),0);}if(code!=='custom'){$('#ReportFrom').val(iso(from));$('#ReportTo').val(iso(to));}}
    function saved(){try{return JSON.parse(localStorage.getItem(storageKey)||'{}');}catch{return {};}}
    function listFilters(){$('#SavedFilter').empty().append('<option value="">Сохранённые фильтры</option>');Object.keys(saved()).sort().forEach(name=>$('#SavedFilter').append($('<option>').val(name).text(name)));}
    $('#SaveFilter').on('click',()=>{const name=$('#FilterName').val().trim();if(!name)return abp.message.warn('Укажите название фильтра.');const filters=saved();filters[name]=input();try{localStorage.setItem(storageKey,JSON.stringify(filters));listFilters();$('#SavedFilter').val(name);}catch{abp.message.warn('Браузер не разрешает сохранять фильтры.');}});
    $('#DeleteFilter').on('click',async()=>{const name=$('#SavedFilter').val();if(!name||!await abp.message.confirm('Удалить сохранённый фильтр?'))return;const filters=saved();delete filters[name];localStorage.setItem(storageKey,JSON.stringify(filters));listFilters();});
    $('#SavedFilter').on('change',async()=>{const f=saved()[$('#SavedFilter').val()];if(!f||!catalog.some(r=>r.code===f.code))return;resetDetail();$('#ReportCode').val(f.code);$('#ReportBranch').val(f.branchId||'');$('#ReportFrom').val(f.from);$('#ReportTo').val(f.to);$('#ReportMonths').val(f.inactiveMonths);$('#ReportPreset').val('custom');groups(f.groupBy);await doctors();$('#ReportDoctor').val(f.doctorId||'');load();});
    $('#ReportBack').on('click',()=>{resetDetail();$('#ReportGrouping').val(previous?.groupBy||'default');load();});$('#ReportCode').on('change',()=>{resetDetail();groups();});$('#ReportGrouping').on('change',resetDetail);$('#ReportBranch').on('change',()=>{resetDetail();doctors().catch(error);});$('#ReportPreset').on('change',()=>{resetDetail();preset();});$('#ReportFrom,#ReportTo').on('change',()=>{$('#ReportPreset').val('custom');resetDetail();});$('#ReportFilter').on('submit',e=>{e.preventDefault();load();});
    async function loadSubscriptions(){const rows=await subscriptions.getList(),table=$('<table class="table">').append('<thead><tr><th>Отчёт</th><th>Расписание</th><th>Канал</th><th>Последняя отправка</th><th>Ошибка</th><th></th></tr></thead>'),body=$('<tbody>');rows.forEach(s=>{const row=$('<tr>');[catalog.find(r=>r.code===s.code)?.name||s.code,(s.frequency==='weekly'?days[s.weekday]:'Ежедневно')+' '+s.localTime,s.channel==='email'?'Email':'В приложении',s.lastSentAt?format(s.lastSentAt,'DateTime'):'—',s.lastError||'—'].forEach(v=>row.append($('<td>').text(v)));row.append($('<td>').append($('<button type="button" class="btn btn-sm btn-outline-primary me-2">').text(s.enabled?'Приостановить':'Включить').on('click',()=>subscriptions.setEnabled(s.id,!s.enabled).then(loadSubscriptions).catch(error)),$('<button type="button" class="btn btn-sm btn-outline-danger">').text('Удалить').on('click',async()=>{if(await abp.message.confirm('Удалить подписку?'))subscriptions.delete(s.id).then(loadSubscriptions).catch(error);})));body.append(row);});$('#Subscriptions').empty().append(table.append(body));}
    $('#SubscriptionFrequency').on('change',()=>$('#SubscriptionWeekday').prop('hidden',$('#SubscriptionFrequency').val()!=='weekly'));
    $('#SubscriptionForm').on('submit',async e=>{e.preventDefault();const b=$('#SubscriptionForm button').prop('disabled',true);try{await subscriptions.create({code:$('#ReportCode').val(),branchId:$('#ReportBranch').val()||null,localTime:$('#SubscriptionTime').val()+':00',channel:$('#SubscriptionChannel').val(),frequency:$('#SubscriptionFrequency').val(),weekday:Number($('#SubscriptionWeekday').val()),groupBy:$('#ReportGrouping').val()});await loadSubscriptions();}catch(ex){error(ex);}finally{b.prop('disabled',false);}});
    preset();listFilters();Promise.all([api.getCatalog(),dental.branches.branch.getLookup()]).then(async v=>{catalog=v[0];const optgroups={};catalog.forEach(r=>{const group=r.permission.startsWith('Dental.Inventory')?'Склад':r.permission==='Dental.Reports.Finance'?'Финансы':r.permission==='Dental.Reports.Network'?'Сеть':r.permission==='Dental.Reports.Payroll'?'Зарплата':'Операционные';if(!optgroups[group])optgroups[group]=$('<optgroup>').attr('label',group).appendTo('#ReportCode');optgroups[group].append($('<option>').val(r.code).text(r.name));});v[1].items.forEach(b=>$('#ReportBranch').append($('<option>').val(b.id).text(b.name)));groups();await doctors();loadSubscriptions().catch(error);await load();}).catch(error);
});
