$(function () {
    'use strict';
    const api=dental.reports.reports;
    const subscriptions=dental.reports.reportSubscription;
    async function loadSubscriptions(){const rows=await subscriptions.getList(),table=$('<table class="table">').append('<thead><tr><th>Отчёт</th><th>Время</th><th>Канал</th><th>Последняя отправка</th><th>Ошибка</th><th></th></tr></thead>'),body=$('<tbody>');rows.forEach(s=>{const row=$('<tr>');[s.code,s.localTime,s.channel,s.lastSentAt?new Date(s.lastSentAt).toLocaleString('ru-RU'):'—',s.lastError||'—'].forEach(v=>row.append($('<td>').text(v)));row.append($('<td>').append($('<button type="button" class="btn btn-sm btn-outline-primary me-2">').text(s.enabled?'Приостановить':'Включить').on('click',()=>subscriptions.setEnabled(s.id,!s.enabled).then(loadSubscriptions).catch(error)),$('<button type="button" class="btn btn-sm btn-outline-danger">').text('Удалить').on('click',async()=>{if(await abp.message.confirm('Удалить подписку?'))subscriptions.delete(s.id).then(loadSubscriptions).catch(error);})));body.append(row);});$('#Subscriptions').empty().append(table.append(body));}
    function input(){return {code:$('#ReportCode').val(),branchId:$('#ReportBranch').val()||null,from:dentalCalendarDates.normalize($('#ReportFrom').val()),to:dentalCalendarDates.normalize($('#ReportTo').val()),inactiveMonths:Number($('#ReportMonths').val())};}
    const error=e=>abp.message.error(e.message||(e.responseJSON&&e.responseJSON.error&&e.responseJSON.error.message)||'Не удалось сформировать отчёт.');
    function format(value,type){if(value==null)return '—';if(type==='DateTime')return new Date(value).toLocaleString('ru-RU');if(type==='Decimal'||type==='Double')return Number(value).toLocaleString('ru-RU',{maximumFractionDigits:2});return String(value);}
    function render(result) {
        const table=$('<table class="table table-striped">'),head=$('<tr>'),body=$('<tbody>');result.columns.forEach(c=>head.append($('<th>').text(c.name)));
        result.rows.forEach(row=>{const tr=$('<tr>');row.forEach((v,n)=>tr.append($('<td>').text(format(v,result.columns[n].type))));body.append(tr);});$('#ReportTable').empty().append(table.append($('<thead>').append(head),body));
        $('#ReportState').text(result.rows.length===0?'Нет данных за выбранный период.':result.rows.length+' строк'+(result.truncated?' · Показаны первые 5000. Сузьте фильтры для полного результата.':''));
        const chart=$('#ReportChart').empty(),index=result.columns.findIndex((c,n)=>n>0&&['Decimal','Double','Int64','Int32'].includes(c.type));
        if(index>=0&&result.rows.length>0){const rows=result.rows.slice(0,20),max=Math.max(1,...rows.map(r=>Math.abs(Number(r[index]||0))));chart.append($('<h5>').text(result.columns[index].name));rows.forEach(r=>{const label=format(r[0],result.columns[0].type),value=Number(r[index]||0);chart.append($('<div class="d-flex gap-2 align-items-center mb-2">').append($('<span class="text-truncate">').css('width','160px').attr('title',label).text(label),$('<div class="flex-grow-1">').append($('<div>').css({height:'16px',width:Math.max(1,Math.abs(value)/max*100)+'%',background:value<0?'#dc3545':'#5549ff','border-radius':'3px'})),$('<span>').text(format(value,result.columns[index].type))));});}
        ['Xlsx','Pdf','Csv'].forEach(f=>{const params=new URLSearchParams({...input(),handler:'Export',format:f.toLowerCase()});if(!input().branchId)params.delete('branchId');$('#Report'+f).attr('href','/Reports?'+params);});
    }
    async function load(){if(!$('#ReportCode').val())return;const b=$('#ReportFilter button').prop('disabled',true);$('#ReportState').text('Формируем отчёт…');try{render(await api.get(input()));}catch(e){$('#ReportState').text('Не удалось загрузить отчёт.');error(e);}finally{b.prop('disabled',false);}}
    const now=new Date(),iso=d=>d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');$('#ReportFrom').val(iso(new Date(now.getFullYear(),now.getMonth(),1)));$('#ReportTo').val(iso(now));
    $('#SubscriptionForm').on('submit',async e=>{e.preventDefault();const b=$('#SubscriptionForm button').prop('disabled',true);try{await subscriptions.create({code:$('#ReportCode').val(),branchId:$('#ReportBranch').val()||null,localTime:$('#SubscriptionTime').val()+':00',channel:$('#SubscriptionChannel').val()});await loadSubscriptions();}catch(ex){error(ex);}finally{b.prop('disabled',false);}});
    $('#ReportFilter').on('submit',e=>{e.preventDefault();load();});Promise.all([api.getCatalog(),dental.branches.branch.getLookup()]).then(v=>{v[0].forEach(r=>$('#ReportCode').append($('<option>').val(r.code).text(r.name)));v[1].items.forEach(b=>$('#ReportBranch').append($('<option>').val(b.id).text(b.name)));loadSubscriptions().catch(error);return load();}).catch(error);
});
