$(function(){
    var api=dental.finance.cash,l=abp.localization.getResource('Dental'),registers=[],shifts=[],categories=[],patients=[],selectedVisit=null,action=null,busy=false;
    var modal=bootstrap.Modal.getOrCreateInstance(document.getElementById('CashModal'));
    function granted(p){return abp.auth.isGranted('Dental.'+p);}function branch(){return $('#CashBranch').val();}
    function load(){if(!branch())return;api.getRegisters(branch()).then(function(r){registers=r;});api.getExpenseCategories().then(function(r){categories=r;});
        api.getShifts(branch()).then(function(r){shifts=r;var root=$('#CashShifts').empty();r.forEach(function(s){var row=$('<tr>').append($('<td>').text(s.registerName),$('<td>').text(dentalUi.dateTime(s.openedAt)),$('<td>').text(l('Finance:ShiftStatus:'+s.status)),$('<td>').text(dentalUi.money(s.expectedCash)),$('<td>').text(s.closingBalanceActual==null?'—':dentalUi.money(s.closingBalanceActual)),$('<td>').text(s.difference==null?'—':dentalUi.money(s.difference)));var tools=$('<td>');if(s.status===0&&granted('Cash.ShiftOpenClose'))tools.append($('<button class="btn btn-sm btn-outline-danger">').text(l('Finance:CloseShift')).on('click',function(){closeShift(s);}));root.append(row.append(tools));});});
        api.getPayments({branchId:branch()}).then(function(r){var root=$('#CashPayments').empty();r.forEach(function(p){var tools=$('<td>');if(p.visitId)tools.append($('<a class="btn btn-sm btn-outline-primary me-2">').attr('href','/Visits/Detail?id='+p.visitId).text(l('Finance:Visit')));if(p.type!==1&&p.state===0&&granted('Cash.PaymentRefund'))tools.append($('<button class="btn btn-sm btn-outline-danger">').text(l('Finance:Refund')).on('click',function(){refund(p);}));root.append($('<tr>').append($('<td>').text(dentalUi.dateTime(p.creationTime)),$('<td>').text(p.patientName),$('<td>').text(l('Finance:Method:'+p.method)),$('<td>').text(l('Finance:PaymentType:'+p.type)),$('<td>').text(dentalUi.money(p.amount)),$('<td>').text(l('Finance:PaymentState:'+p.state)),tools));});});
        api.getExpenses({branchId:branch()}).then(function(r){var root=$('#CashExpenses').empty();r.forEach(function(e){root.append($('<tr>').append($('<td>').text(dentalUi.dateTime(e.paidAt)),$('<td>').text(e.categoryName),$('<td>').text(dentalUi.money(e.amount)),$('<td>').text(e.comment||'')));});});}
    function dialog(title,submit){$('#CashFields').empty();$('#CashModalTitle').text(l(title));action=submit;modal.show();}
    function field(name,label,type,value,required){var input=$('<input class="form-control">').attr({id:'CashInput_'+name,name:name,type:type||'text'}).val(value==null?'':value).prop('required',required!==false);if(type==='number')input.attr({min:0,step:.01});$('#CashFields').append($('<div class="mb-3">').append($('<label class="form-label">').attr('for',input.attr('id')).text(l(label)),input));return input;}
    function select(name,label,rows){var input=$('<select class="form-select" required>').attr({name:name,id:'CashInput_'+name});rows.forEach(function(r){input.append($('<option>').val(r.id).text(r.name));});$('#CashFields').append($('<div class="mb-3">').append($('<label class="form-label">').attr('for',input.attr('id')).text(l(label)),input));return input;}
    function val(name){return $('#CashInput_'+name).val();}function money(name){return Math.round(Number(val(name))*100);}function openShifts(){return shifts.filter(function(s){return s.status===0;}).map(function(s){return {id:s.id,name:s.registerName+' · '+dentalUi.dateTime(s.openedAt)};});}
    function shiftField(){return select('shiftId','Finance:Shifts',openShifts());}
    function closeShift(s){dialog('Finance:CloseShift',function(){return api.closeShift(s.id,{concurrencyStamp:s.concurrencyStamp,actual:money('actual'),comment:val('comment')});});field('expected','Finance:ExpectedCash','text',dentalUi.money(s.expectedCash),false).prop('disabled',true);field('actual','Finance:ActualCash','number',s.expectedCash/100);field('comment','Finance:Comment','text','',false);}
    $('#CashNewRegister').toggle(granted('Org.SettingsManage')).on('click',function(){dialog('Finance:NewRegister',function(){return api.createRegister({branchId:branch(),name:val('name')});});field('name','Finance:Register');});
    $('#CashOpenShift').toggle(granted('Cash.ShiftOpenClose')).on('click',function(){dialog('Finance:OpenShift',function(){return api.openShift({cashRegisterId:val('registerId'),openingBalance:money('opening')});});select('registerId','Finance:Register',registers);field('opening','Finance:OpeningBalance','number',0);});
    function pay(){var key=crypto.randomUUID();dialog('Finance:Pay',function(){var parts=[{method:Number(val('method')),amount:money('amount')}];if(money('secondAmount')>0)parts.push({method:Number(val('secondMethod')),amount:money('secondAmount')});return api.pay({shiftId:val('shiftId'),patientId:val('patientId'),visitId:val('visitId')||null,parts:parts,idempotencyKey:key,comment:val('comment')});});shiftField();
        var patient=select('patientId','Finance:Patient',selectedVisit?[{id:selectedVisit.patientId,name:selectedVisit.patientName}]:patients),visit=select('visitId','Finance:Visit',[{id:'',name:l('Finance:Advance')}]);
        function visits(){visit.empty().append($('<option>').val('').text(l('Finance:Advance')));dental.finance.visit.getList({branchId:branch(),patientId:patient.val()}).then(function(r){r.filter(function(v){return v.status!==2;}).forEach(function(v){visit.append($('<option>').val(v.id).text(dentalUi.dateTime(v.openedAt)+' · '+dentalUi.money(v.debt)));});if(selectedVisit)visit.val(selectedVisit.id);});}patient.on('change',visits);visits();
        var methods=[0,1,2,3,4,5].map(function(i){return{id:i,name:l('Finance:Method:'+i)};});select('method','Finance:Method',methods);field('amount','Finance:Amount','number',selectedVisit?selectedVisit.debt/100:0);select('secondMethod','Finance:SecondMethod',methods);field('secondAmount','Finance:SecondAmount','number',0,false);field('comment','Finance:Comment','text','',false);}
    $('#CashPay').toggle(granted('Cash.PaymentCreate')).on('click',pay);
    function refund(p){var key=crypto.randomUUID();dialog('Finance:Refund',function(){return api.refund(p.id,{shiftId:val('shiftId'),amount:money('amount'),reason:val('reason'),idempotencyKey:key});});shiftField();field('amount','Finance:Amount','number',p.amount/100);field('reason','Finance:Reason');}
    $('#CashExpense').toggle(granted('Cash.ExpenseCreate')).on('click',function(){dialog('Finance:Expense',function(){return api.createExpense({branchId:branch(),categoryId:val('categoryId'),amount:money('amount'),shiftId:val('shiftId')||null,counterparty:val('counterparty'),comment:val('comment')});});select('categoryId','Finance:Category',categories);select('shiftId','Finance:PaidFrom',[{id:'',name:l('Finance:NonCash')}].concat(openShifts()));field('amount','Finance:Amount','number');field('counterparty','Finance:Counterparty','text','',false);field('comment','Finance:Comment','text','',false);});
    $('#CashOperation').toggle(granted('Cash.ShiftOpenClose')).on('click',function(){dialog('Finance:CashOperation',function(){return api.createOperation({shiftId:val('shiftId'),type:Number(val('type')),amount:money('amount'),comment:val('comment')});});shiftField();select('type','Finance:Type',[{id:0,name:l('Finance:Collection')},{id:1,name:l('Finance:Deposit')}]);field('amount','Finance:Amount','number');field('comment','Finance:Comment');});
    $('#CashCategory').toggle(granted('Org.SettingsManage')).on('click',function(){dialog('Finance:NewCategory',function(){return api.createExpenseCategory({name:val('name'),type:Number(val('type'))});});field('name','Finance:Category');select('type','Finance:Type',[0,1,2,3,4,5,6].map(function(i){return {id:i,name:l('Finance:ExpenseType:'+i)};}));});
    $('#CashForm').on('submit',function(e){e.preventDefault();if(busy||!action)return;busy=true;$('#CashSubmit').prop('disabled',true);action().then(function(){modal.hide();load();}).always(function(){busy=false;$('#CashSubmit').prop('disabled',false);});});$('#CashBranch').on('change',function(){selectedVisit=null;load();});
    dental.patients.patient.getLookup('',200).then(function(r){patients=r.items.map(function(p){return {id:p.id,name:p.name||p.fullName};});});
    dental.branches.branch.getLookup().then(function(r){r.items.forEach(function(b){$('#CashBranch').append($('<option>').val(b.id).text(b.name));});var visitId=new URLSearchParams(location.search).get('visitId');if(visitId)dental.finance.visit.get(visitId).then(function(v){selectedVisit=v;$('#CashBranch').val(v.branchId);load();});else load();});
});
