using System;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Dental.EntityFrameworkCore;
using Dental.Reports;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;
using Volo.Abp.DependencyInjection;
using Volo.Abp.EntityFrameworkCore;
namespace Dental.Reports;
public partial class SqlReportStore(IDbContextProvider<DentalDbContext> provider) : IReportStore, ITransientDependency
{
    // Every CTE explicitly enforces tenant and branch scope, including all joined lookups.
    private const string Common = """
        WITH b AS (SELECT * FROM "AppBranches" WHERE "TenantId"=@tenant AND NOT "IsDeleted" AND "Id"=ANY(@branches)),
        d AS (SELECT * FROM "AppEmployees" WHERE "TenantId"=@tenant AND NOT "IsDeleted"),
        p AS (SELECT * FROM "AppPatients" WHERE "TenantId"=@tenant AND NOT "IsDeleted" AND "MergedIntoId" IS NULL),
        a_all AS (SELECT * FROM "AppAppointments" WHERE "TenantId"=@tenant AND NOT "IsDeleted" AND "BranchId"=ANY(@branches) AND (@doctor IS NULL OR "DoctorId"=@doctor)),
        a AS (SELECT * FROM a_all WHERE "StartsAt">=@from AND "StartsAt"<@to),
        v_all AS (SELECT visit.* FROM "AppVisits" visit WHERE visit."TenantId"=@tenant AND NOT visit."IsDeleted" AND visit."BranchId"=ANY(@branches) AND visit."Status"=1 AND (@doctor IS NULL OR visit."DoctorId"=@doctor OR EXISTS (SELECT 1 FROM "AppVisitItems" item WHERE item."TenantId"=@tenant AND NOT item."IsDeleted" AND item."VisitId"=visit."Id" AND item."DoctorId"=@doctor))),
        v AS (SELECT * FROM v_all WHERE "ClosedAt">=@from AND "ClosedAt"<@to),
        vi AS (SELECT i.* FROM "AppVisitItems" i JOIN v ON v."Id"=i."VisitId" WHERE i."TenantId"=@tenant AND NOT i."IsDeleted" AND (@doctor IS NULL OR i."DoctorId"=@doctor)),
        vm AS (SELECT m.* FROM "AppVisitMaterials" m JOIN v ON v."Id"=m."VisitId" WHERE m."TenantId"=@tenant AND NOT m."IsDeleted"),
        pay AS (SELECT * FROM "AppPayments" WHERE "TenantId"=@tenant AND NOT "IsDeleted" AND "State"=0 AND "Method"<>5 AND "BranchId"=ANY(@branches) AND "CreationTime">=@from AND "CreationTime"<@to),
        w AS (SELECT * FROM "AppWarehouses" WHERE "TenantId"=@tenant AND NOT "IsDeleted" AND ("BranchId"=ANY(@branches) OR (@central AND "BranchId" IS NULL))),
        i AS (SELECT * FROM "AppItems" WHERE "TenantId"=@tenant AND NOT "IsDeleted"),
        mov AS (SELECT m.* FROM "AppStockMovements" m JOIN w ON w."Id"=m."WarehouseId" WHERE m."TenantId"=@tenant AND m."MovedAt"<@to),
        sd AS (SELECT * FROM "AppStockDocuments" WHERE "TenantId"=@tenant AND NOT "IsDeleted" AND ("BranchId"=ANY(@branches) OR (@central AND "BranchId" IS NULL))),
        sl AS (SELECT l.* FROM "AppStockDocumentLines" l JOIN sd ON sd."Id"=l."DocumentId" ),
        pp AS (SELECT * FROM "AppPayrollPeriods" WHERE "TenantId"=@tenant AND NOT "IsDeleted" AND "BranchId"=ANY(@branches) AND "Status"<>0 AND "PeriodStart"<(@to AT TIME ZONE 'UTC' AT TIME ZONE @tz)::date AND "PeriodEnd">=(@from AT TIME ZONE 'UTC' AT TIME ZONE @tz)::date),
        pe AS (SELECT e.* FROM "AppPayrollEntries" e JOIN pp ON pp."Id"=e."PeriodId" WHERE e."TenantId"=@tenant AND NOT e."IsDeleted" AND (@doctor IS NULL OR e."EmployeeId"=@doctor)),
        dates AS (SELECT g::date local_date FROM generate_series((@from AT TIME ZONE 'UTC' AT TIME ZONE @tz)::date,(@to AT TIME ZONE 'UTC' AT TIME ZONE @tz)::date-1,interval '1 day') g),
        sx AS (SELECT * FROM "AppScheduleExceptions" WHERE "TenantId"=@tenant AND NOT "IsDeleted" AND ("BranchId"=ANY(@branches) OR "BranchId" IS NULL) AND (@doctor IS NULL OR "DoctorId"=@doctor)),
        raw_work AS (
          SELECT s."DoctorId" doctor,s."BranchId" branch,dates.local_date,tsrange((dates.local_date+s."StartTime") AT TIME ZONE @tz AT TIME ZONE 'UTC',(dates.local_date+s."EndTime") AT TIME ZONE @tz AT TIME ZONE 'UTC','[)') span
          FROM "AppDoctorSchedules" s JOIN dates ON extract(dow FROM dates.local_date)=s."Weekday" AND dates.local_date>=s."ValidFrom" AND (s."ValidTo" IS NULL OR dates.local_date<=s."ValidTo") WHERE s."TenantId"=@tenant AND NOT s."IsDeleted" AND s."BranchId"=ANY(@branches) AND (@doctor IS NULL OR s."DoctorId"=@doctor)
          UNION ALL SELECT sx."DoctorId",b."Id",dates.local_date,tsrange((dates.local_date+sx."StartTime") AT TIME ZONE @tz AT TIME ZONE 'UTC',(dates.local_date+sx."EndTime") AT TIME ZONE @tz AT TIME ZONE 'UTC','[)') FROM sx JOIN dates ON dates.local_date BETWEEN sx."DateFrom" AND sx."DateTo" JOIN b ON sx."BranchId" IS NULL OR sx."BranchId"=b."Id" WHERE sx."Type"=3
        ),
        work_ranges AS (SELECT doctor,branch,local_date,range_agg(span)-coalesce((SELECT range_agg(tsrange((raw_work.local_date+coalesce(sx."StartTime",'00:00'::time)) AT TIME ZONE @tz AT TIME ZONE 'UTC',(raw_work.local_date+coalesce(sx."EndTime",'00:00'::time)+CASE WHEN sx."EndTime" IS NULL THEN interval '1 day' ELSE interval '0' END) AT TIME ZONE @tz AT TIME ZONE 'UTC','[)')) FROM sx WHERE sx."DoctorId"=raw_work.doctor AND (sx."BranchId" IS NULL OR sx."BranchId"=raw_work.branch) AND raw_work.local_date BETWEEN sx."DateFrom" AND sx."DateTo" AND sx."Type"<>3),'{}'::tsmultirange) spans FROM raw_work GROUP BY doctor,branch,local_date),
        capacity AS (SELECT doctor,branch,local_date,sum(extract(epoch FROM upper(span)-lower(span)))/60 minutes FROM work_ranges CROSS JOIN LATERAL unnest(spans) span GROUP BY doctor,branch,local_date),
        occupied AS (SELECT "DoctorId" doctor,"BranchId" branch,("StartsAt" AT TIME ZONE 'UTC' AT TIME ZONE @tz)::date local_date,sum(extract(epoch FROM least("EndsAt",@to)-greatest("StartsAt",@from)))/60 minutes FROM a WHERE "Status" NOT IN(5,6) GROUP BY 1,2,3)
        """;
    private static string Query(string code) => code switch
    {
        "appointments_summary" => """SELECT (a."StartsAt" AT TIME ZONE 'UTC' AT TIME ZONE @tz)::date AS "Дата",d."FullName" AS "Врач",count(*) AS "Записи",count(*) FILTER(WHERE a."Status"=0) AS "Не подтверждены",count(*) FILTER(WHERE a."Status"=1) AS "Подтверждены",count(*) FILTER(WHERE a."Status" IN(2,3)) AS "В клинике",count(*) FILTER(WHERE a."Status"=4) AS "Завершены",count(*) FILTER(WHERE a."Status"=5) AS "Отмены",count(*) FILTER(WHERE a."Status"=6) AS "Неявки",round(100.0*count(*) FILTER(WHERE a."Status"=6)/greatest(count(*),1),2) AS "Неявки, %",round(100.0*count(*) FILTER(WHERE a."Status"=5)/greatest(count(*),1),2) AS "Отмены, %" FROM a JOIN d ON d."Id"=a."DoctorId" GROUP BY 1,2 ORDER BY 1,2""",
        "cancellations" => """SELECT coalesce(r."Name",a."CancelComment",'Без причины') AS "Причина",count(*) FILTER(WHERE a."Status"=5) AS "Отмены",count(*) FILTER(WHERE a."MoveReasonId" IS NOT NULL) AS "Переносы" FROM a LEFT JOIN "AppCancelReasons" r ON r."Id"=a."CancelReasonId" AND r."TenantId"=@tenant WHERE a."Status"=5 OR a."MoveReasonId" IS NOT NULL GROUP BY 1""",
        "utilization" => """SELECT d."FullName" AS "Врач",b."Name" AS "Филиал",coalesce(c.local_date,o.local_date) AS "Дата",round(coalesce(o.minutes,0),1) AS "Занято, мин",round(coalesce(c.minutes,0),1) AS "По графику, мин",round(100*coalesce(o.minutes,0)/nullif(c.minutes,0),2) AS "Загрузка, %" FROM capacity c FULL JOIN occupied o ON o.doctor=c.doctor AND o.branch=c.branch AND o.local_date=c.local_date JOIN d ON d."Id"=coalesce(c.doctor,o.doctor) JOIN b ON b."Id"=coalesce(c.branch,o.branch) ORDER BY 3,1,2""",
        "patients_flow" => """SELECT coalesce(s."Name",'Не указан') AS "Источник", count(DISTINCT v."PatientId") AS "Пациенты",count(DISTINCT v."PatientId") FILTER(WHERE p."CreationTime">=@from AND p."CreationTime"<@to) AS "Новые",count(DISTINCT v."PatientId") FILTER(WHERE p."CreationTime"<@from) AS "Повторные" FROM v JOIN p ON p."Id"=v."PatientId" LEFT JOIN "AppLeadSources" s ON s."Id"=p."SourceId" AND s."TenantId"=@tenant GROUP BY 1""",
        "lost_patients" => """SELECT concat_ws(' ',p."LastName",p."FirstName",p."MiddleName") AS "Пациент",p."Phone" AS "Телефон",max(v_all."ClosedAt") AS "Последний визит" FROM p JOIN v_all ON v_all."PatientId"=p."Id" GROUP BY p."Id",p."LastName",p."FirstName",p."MiddleName",p."Phone" HAVING max(v_all."ClosedAt")<@to-make_interval(months=>@months) AND NOT EXISTS(SELECT 1 FROM a_all x WHERE x."PatientId"=p."Id" AND x."StartsAt">=@to AND x."Status" NOT IN(5,6)) ORDER BY 3""",
        "revenue" => """SELECT report_day AS "Дата",sum(revenue)/100.0 AS "Выручка, ₸",sum(received)/100.0 AS "Поступления, ₸",sum(visits) AS "Визиты",round(sum(revenue)/100.0/greatest(sum(visits),1),2) AS "Средний чек, ₸" FROM (SELECT ("ClosedAt" AT TIME ZONE 'UTC' AT TIME ZONE @tz)::date report_day,"Total" revenue,0::bigint received,1 visits FROM v UNION ALL SELECT ("CreationTime" AT TIME ZONE 'UTC' AT TIME ZONE @tz)::date,0,CASE WHEN "Type"=1 THEN -"Amount" ELSE "Amount" END,0 FROM pay) z GROUP BY report_day ORDER BY report_day""",
        "payments_by_method" => """SELECT CASE "Method" WHEN 0 THEN 'Наличные' WHEN 1 THEN 'Карта' WHEN 2 THEN 'Kaspi QR' WHEN 3 THEN 'Перевод' WHEN 4 THEN 'Страховая' ELSE 'Другой' END AS "Способ",sum("Amount") FILTER(WHERE "Type"<>1)/100.0 AS "Поступления, ₸",coalesce(sum("Amount") FILTER(WHERE "Type"=1),0)/100.0 AS "Возвраты, ₸" FROM pay GROUP BY 1 ORDER BY 1""",
        "patient_debts" => """SELECT concat_ws(' ',p."LastName",p."FirstName",p."MiddleName") AS "Пациент",sum(greatest(0,v_all."Total"-v_all."PaidTotal"))/100.0 AS "Долг, ₸",sum(greatest(0,v_all."Total"-v_all."PaidTotal")) FILTER(WHERE v_all."ClosedAt">=@to-interval '30 days')/100.0 AS "0–30 дней, ₸",sum(greatest(0,v_all."Total"-v_all."PaidTotal")) FILTER(WHERE v_all."ClosedAt"<@to-interval '30 days' AND v_all."ClosedAt">=@to-interval '90 days')/100.0 AS "31–90 дней, ₸",sum(greatest(0,v_all."Total"-v_all."PaidTotal")) FILTER(WHERE v_all."ClosedAt"<@to-interval '90 days')/100.0 AS "90+ дней, ₸" FROM v_all JOIN p ON p."Id"=v_all."PatientId" WHERE v_all."Total">v_all."PaidTotal" GROUP BY p."Id",1""",
        "advances" => """SELECT concat_ws(' ',p."LastName",p."FirstName",p."MiddleName") AS "Пациент",pb."Balance"/100.0 AS "Баланс, ₸" FROM "AppPatientBalances" pb JOIN p ON p."Id"=pb."PatientId" WHERE pb."TenantId"=@tenant AND pb."Balance">0 AND (EXISTS(SELECT 1 FROM a_all WHERE "PatientId"=p."Id") OR EXISTS(SELECT 1 FROM v_all WHERE "PatientId"=p."Id"))""",
        "cash_shifts" => """SELECT r."Name" AS "Касса",s."OpenedAt" AS "Открыта",s."ClosedAt" AS "Закрыта",s."OpeningBalance"/100.0 AS "На начало, ₸",s."ClosingBalanceExpected"/100.0 AS "Ожидалось, ₸",s."ClosingBalanceActual"/100.0 AS "Факт, ₸",s."Difference"/100.0 AS "Разница, ₸" FROM "AppCashShifts" s JOIN "AppCashRegisters" r ON r."Id"=s."CashRegisterId" AND r."TenantId"=@tenant WHERE s."TenantId"=@tenant AND NOT s."IsDeleted" AND s."BranchId"=ANY(@branches) AND s."OpenedAt">=@from AND s."OpenedAt"<@to ORDER BY s."OpenedAt" """,
        "discounts" => """SELECT d."FullName" AS "Врач",sum(vi."DiscountAmount")/100.0 AS "Скидки, ₸",max(vi."DiscountPct") AS "Максимум, %",count(*) AS "Строки услуг" FROM vi JOIN d ON d."Id"=vi."DoctorId" WHERE vi."DiscountAmount">0 GROUP BY 1""",
        "service_margin" => """SELECT s."Name" AS "Услуга",sum(vi."Qty") AS "Количество",sum(vi."Total")/100.0 AS "Выручка, ₸",coalesce(sum(mc.cost),0)/100.0 AS "Материалы, ₸",(sum(vi."Total")-coalesce(sum(mc.cost),0))/100.0 AS "Маржа, ₸",round(100.0*(sum(vi."Total")-coalesce(sum(mc.cost),0))/greatest(sum(vi."Total"),1),2) AS "Маржа, %" FROM vi JOIN "AppServices" s ON s."Id"=vi."ServiceId" AND s."TenantId"=@tenant LEFT JOIN (SELECT "VisitItemId",sum("Cost") cost FROM vm GROUP BY 1) mc ON mc."VisitItemId"=vi."Id" GROUP BY 1""",
        "pnl" => """SELECT b."Name" AS "Филиал",coalesce(x.rev,0)/100.0 AS "Выручка, ₸",coalesce(x.mat,0)/100.0 AS "Материалы, ₸",coalesce(ex.amount,0)/100.0 AS "Расходы без зарплаты, ₸",coalesce(pr.amount,0)/100.0 AS "Зарплата, ₸",(coalesce(x.rev,0)-coalesce(x.mat,0)-coalesce(ex.amount,0)-coalesce(pr.amount,0))/100.0 AS "Результат, ₸" FROM b LEFT JOIN (SELECT v."BranchId",sum(v."Total") rev,sum(coalesce(mc.cost,0)) mat FROM v LEFT JOIN (SELECT "VisitId",sum("Cost") cost FROM vm GROUP BY 1) mc ON mc."VisitId"=v."Id" GROUP BY 1) x ON x."BranchId"=b."Id" LEFT JOIN (SELECT e."BranchId",sum(e."Amount") amount FROM "AppExpenses" e JOIN "AppExpenseCategories" c ON c."Id"=e."CategoryId" AND c."TenantId"=@tenant WHERE e."TenantId"=@tenant AND NOT e."IsDeleted" AND c."Type"<>2 AND e."PaidAt">=@from AND e."PaidAt"<@to GROUP BY 1) ex ON ex."BranchId"=b."Id" LEFT JOIN (SELECT pp."BranchId",sum(pe."Total") amount FROM pe JOIN pp ON pp."Id"=pe."PeriodId" GROUP BY 1) pr ON pr."BranchId"=b."Id" """,
        "doctor_performance" => """SELECT d."FullName" AS "Врач",count(DISTINCT vi."VisitId") AS "Визиты",count(DISTINCT v."PatientId") AS "Пациенты",sum(vi."Total")/100.0 AS "Выручка, ₸",round(sum(vi."Total")/100.0/greatest(count(DISTINCT vi."VisitId"),1),2) AS "Средний чек, ₸" FROM vi JOIN v ON v."Id"=vi."VisitId" JOIN d ON d."Id"=vi."DoctorId" GROUP BY 1""",
        "stock_on_date" => """SELECT w."Name" AS "Склад",i."Name" AS "Товар",sum(mov."Qty") AS "Остаток",round(sum(mov."Qty"*mov."UnitCost")/100,2) AS "Стоимость, ₸" FROM mov JOIN w ON w."Id"=mov."WarehouseId" JOIN i ON i."Id"=mov."ItemId" GROUP BY 1,2 HAVING sum(mov."Qty")<>0 ORDER BY 1,2""",
        "stock_movement" => """SELECT w."Name" AS "Склад",i."Name" AS "Товар",coalesce(sum(mov."Qty") FILTER(WHERE mov."MovedAt"<@from),0) AS "На начало",coalesce(sum(mov."Qty") FILTER(WHERE mov."MovedAt">=@from AND mov."Qty">0),0) AS "Приход",coalesce(-sum(mov."Qty") FILTER(WHERE mov."MovedAt">=@from AND mov."Qty"<0 AND mov."DocumentType"=5),0) AS "Визиты",coalesce(-sum(mov."Qty") FILTER(WHERE mov."MovedAt">=@from AND mov."Qty"<0 AND mov."DocumentType"=2),0) AS "Списания",coalesce(sum(mov."Qty") FILTER(WHERE mov."MovedAt">=@from AND mov."DocumentType"=1),0) AS "Перемещения, нетто",sum(mov."Qty") AS "На конец" FROM mov JOIN w ON w."Id"=mov."WarehouseId" JOIN i ON i."Id"=mov."ItemId" GROUP BY 1,2 ORDER BY 1,2""",
        "consumption" => """SELECT d."FullName" AS "Врач",i."Name" AS "Материал",sum(vm."Quantity") AS "Факт",sum(vm."NormQuantity") AS "Норма",sum(vm."Quantity"-vm."NormQuantity") AS "Отклонение",sum(vm."Cost")/100.0 AS "Стоимость, ₸" FROM vm JOIN v ON v."Id"=vm."VisitId" LEFT JOIN vi ON vi."Id"=vm."VisitItemId" JOIN d ON d."Id"=coalesce(vi."DoctorId",v."DoctorId") JOIN i ON i."Id"=vm."ItemId" WHERE @doctor IS NULL OR d."Id"=@doctor GROUP BY 1,2""",
        "writeoffs" => """SELECT coalesce(r."Name",'Без причины') AS "Причина",i."Name" AS "Товар",sum(sl."Qty") AS "Количество",sum(sl."TotalCost")/100.0 AS "Стоимость, ₸" FROM sd JOIN sl ON sl."DocumentId"=sd."Id" JOIN i ON i."Id"=sl."ItemId" LEFT JOIN "AppWriteoffReasons" r ON r."Id"=sd."ReasonId" AND r."TenantId"=@tenant WHERE sd."Type"=2 AND sd."Status"=2 AND sd."PostedAt">=@from AND sd."PostedAt"<@to GROUP BY 1,2""",
        "expiring" => """SELECT w."Name" AS "Склад",i."Name" AS "Товар",bt."BatchNumber" AS "Партия",bt."ExpiresAt" AS "Годен до",sum(mov."Qty") AS "Остаток" FROM mov JOIN w ON w."Id"=mov."WarehouseId" JOIN i ON i."Id"=mov."ItemId" JOIN "AppBatches" bt ON bt."Id"=mov."BatchId" AND bt."TenantId"=@tenant WHERE bt."ExpiresAt"<=(@to AT TIME ZONE 'UTC' AT TIME ZONE @tz)::date+30 GROUP BY 1,2,3,4 HAVING sum(mov."Qty")>0 ORDER BY 4""",
        "inventory_discrepancies" => """SELECT sd."Number" AS "Документ",i."Name" AS "Товар",sl."ExpectedQty" AS "Ожидалось",sl."ActualQty" AS "Факт",sl."ActualQty"-sl."ExpectedQty" AS "Разница",round((sl."ActualQty"-sl."ExpectedQty")*sl."UnitCost"/100,2) AS "Разница, ₸" FROM sd JOIN sl ON sl."DocumentId"=sd."Id" JOIN i ON i."Id"=sl."ItemId" WHERE sd."Type"=3 AND sd."Status"=2 AND sd."PostedAt">=@from AND sd."PostedAt"<@to ORDER BY 1,2""",
        "abc_analysis" => """SELECT name AS "Товар",round(cost/100,2) AS "Расход, ₸",round(100*cost/nullif(sum(cost) OVER(),0),2) AS "Доля, %",CASE WHEN sum(cost) OVER(ORDER BY cost DESC ROWS UNBOUNDED PRECEDING)/nullif(sum(cost) OVER(),0)<=0.8 THEN 'A' WHEN sum(cost) OVER(ORDER BY cost DESC ROWS UNBOUNDED PRECEDING)/nullif(sum(cost) OVER(),0)<=0.95 THEN 'B' ELSE 'C' END AS "Класс" FROM (SELECT i."Name" name,-sum(mov."Qty"*mov."UnitCost") cost FROM mov JOIN i ON i."Id"=mov."ItemId" WHERE mov."Qty"<0 AND mov."DocumentType" IN(2,5) AND mov."MovedAt">=@from GROUP BY 1) x ORDER BY cost DESC""",
        "in_transit" => """SELECT sd."Number" AS "Документ",i."Name" AS "Товар",sl."Qty" AS "В пути",sd."PostedAt" AS "Отправлен" FROM sd JOIN sl ON sl."DocumentId"=sd."Id" JOIN i ON i."Id"=sl."ItemId" WHERE sd."Type"=1 AND sd."Status"=3 ORDER BY 1,2""",
        "purchases" => """SELECT s."Name" AS "Поставщик",i."Name" AS "Товар",sum(sl."Qty") AS "Количество",sum(sl."TotalCost")/100.0 AS "Стоимость, ₸",round(sum(sl."TotalCost")/100.0/nullif(sum(sl."Qty"),0),2) AS "Средняя цена, ₸" FROM sd JOIN sl ON sl."DocumentId"=sd."Id" JOIN i ON i."Id"=sl."ItemId" JOIN "AppSuppliers" s ON s."Id"=sd."SupplierId" AND s."TenantId"=@tenant WHERE sd."Type"=0 AND sd."Status"=2 AND sd."PostedAt">=@from AND sd."PostedAt"<@to GROUP BY 1,2""",
        "branches_comparison" => """SELECT b."Name" AS "Филиал",coalesce(x.revenue,0)/100.0 AS "Выручка, ₸",coalesce(x.visits,0) AS "Визиты",coalesce(x.patients,0) AS "Пациенты",round(coalesce(x.revenue,0)/100.0/greatest(coalesce(x.visits,0),1),2) AS "Средний чек, ₸",coalesce(ac.no_show,0) AS "Неявки",coalesce(mc.cost,0)/100.0 AS "Материалы, ₸",(coalesce(x.revenue,0)-coalesce(mc.cost,0))/100.0 AS "Маржа, ₸" FROM b LEFT JOIN (SELECT "BranchId",sum("Total") revenue,count(*) visits,count(DISTINCT "PatientId") patients FROM v GROUP BY 1) x ON x."BranchId"=b."Id" LEFT JOIN (SELECT "BranchId",count(*) FILTER(WHERE "Status"=6) no_show FROM a GROUP BY 1) ac ON ac."BranchId"=b."Id" LEFT JOIN (SELECT v."BranchId",sum(vm."Cost") cost FROM vm JOIN v ON v."Id"=vm."VisitId" GROUP BY 1) mc ON mc."BranchId"=b."Id" """,
        "payroll" => """SELECT d."FullName" AS "Сотрудник",pp."PeriodStart" AS "Начало",pp."PeriodEnd" AS "Конец",pe."BaseRevenue"/100.0 AS "Выручка, ₸",pe."MaterialsCost"/100.0 AS "Материалы, ₸",pe."Accrued"/100.0 AS "Начислено, ₸",pe."Bonus"/100.0 AS "Бонус, ₸",pe."Penalty"/100.0 AS "Штраф, ₸",pe."Total"/100.0 AS "Итого, ₸" FROM pe JOIN pp ON pp."Id"=pe."PeriodId" JOIN d ON d."Id"=pe."EmployeeId" ORDER BY 1,2""",
        "daily_summary" => """SELECT b."Name" AS "Филиал",coalesce((SELECT sum("Total") FROM v WHERE "BranchId"=b."Id"),0)/100.0 AS "Выручка, ₸",coalesce((SELECT sum(CASE WHEN "Type"=1 THEN -"Amount" ELSE "Amount" END) FROM pay WHERE "BranchId"=b."Id"),0)/100.0 AS "Поступления, ₸",(SELECT count(*) FROM a_all WHERE "BranchId"=b."Id" AND "StartsAt">=@to AND "StartsAt"<@to+interval '1 day' AND "Status" NOT IN(5,6)) AS "Записи завтра",(SELECT count(*) FROM a WHERE "BranchId"=b."Id" AND "Status"=6) AS "Неявки",(SELECT count(*) FROM "AppItemStockLevels" l JOIN w ON w."Id"=l."WarehouseId" WHERE w."BranchId"=b."Id" AND coalesce((SELECT sum(sb."Qty") FROM "AppStockBalances" sb WHERE sb."TenantId"=@tenant AND sb."WarehouseId"=l."WarehouseId" AND sb."ItemId"=l."ItemId"),0)<l."MinQty") AS "Ниже минимума",(SELECT count(DISTINCT n."EntityId") FROM "AppNotifications" n WHERE n."TenantId"=@tenant AND n."Type"='Suspicious' AND n."CreationTime">=@from AND n."CreationTime"<@to AND (n."EntityId" IN(SELECT "Id" FROM "AppVisits" WHERE "TenantId"=@tenant AND "BranchId"=b."Id") OR n."EntityId" IN(SELECT "Id" FROM "AppCashShifts" WHERE "TenantId"=@tenant AND "BranchId"=b."Id") OR n."EntityId" IN(SELECT "Id" FROM "AppPayments" WHERE "TenantId"=@tenant AND "BranchId"=b."Id") OR n."EntityId" IN(SELECT "Id" FROM "AppStockDocuments" WHERE "TenantId"=@tenant AND "BranchId"=b."Id") OR n."EntityId" IN(SELECT "Id" FROM "AppEmployees" WHERE "TenantId"=@tenant AND b."Id"=ANY("BranchIds")))) AS "Подозрительные операции" FROM b ORDER BY 1""",
        _ => throw new ArgumentException("Unknown report",nameof(code))
    };
    public async Task<ReportTable> ExecuteAsync(ReportQuery q)
    {
        var db=await provider.GetDbContextAsync(); var connection=db.Database.GetDbConnection(); if (connection.State != ConnectionState.Open) await db.Database.OpenConnectionAsync();
        await using var command=connection.CreateCommand(); command.Transaction=db.Database.CurrentTransaction?.GetDbTransaction(); command.CommandTimeout=60;
        command.CommandText=Common+ExtendedCommon+" SELECT * FROM ("+(ExtendedQuery(q) ?? Query(q.Code))+") report LIMIT 5001";
        void P(string name, object value) { var p=command.CreateParameter();p.ParameterName=name;p.Value=value;command.Parameters.Add(p); }
        P("tenant",q.TenantId);P("branches",q.BranchIds);P("doctor",q.DoctorId ?? (object)DBNull.Value); ((Npgsql.NpgsqlParameter)command.Parameters["doctor"]).NpgsqlDbType=NpgsqlTypes.NpgsqlDbType.Uuid;
        P("central",q.IncludeCentral);P("from",DateTime.SpecifyKind(q.FromUtc,DateTimeKind.Unspecified));P("to",DateTime.SpecifyKind(q.ToUtc,DateTimeKind.Unspecified));P("tz",q.Timezone);P("months",q.InactiveMonths);
        P("key",q.DetailKey ?? (object)DBNull.Value); ((Npgsql.NpgsqlParameter)command.Parameters["key"]).NpgsqlDbType=NpgsqlTypes.NpgsqlDbType.Text;
        var result=new ReportTable{Timezone=q.Timezone}; await using var reader=await command.ExecuteReaderAsync();
        var visible=Enumerable.Range(0,reader.FieldCount).Where(n=>!reader.GetName(n).StartsWith('_')).ToArray();
        foreach(var n in visible) result.Columns.Add(new(reader.GetName(n),reader.GetDataTypeName(n)=="date"?"DateOnly":reader.GetFieldType(n).Name));
        var keyIndex=Enumerable.Range(0,reader.FieldCount).FirstOrDefault(n=>reader.GetName(n)=="_key",-1);
        var linkIndex=Enumerable.Range(0,reader.FieldCount).FirstOrDefault(n=>reader.GetName(n)=="_link",-1);
        while(await reader.ReadAsync())
        {
            if(result.Rows.Count==5000){result.Truncated=true;break;}
            result.Rows.Add(visible.Select(n=>reader.IsDBNull(n)?null:reader.GetDataTypeName(n)=="date"?(object)reader.GetFieldValue<DateOnly>(n):reader.GetValue(n) is DateTime date?(object)DateTime.SpecifyKind(date,DateTimeKind.Utc):reader.GetValue(n)).ToList());
            result.DrillKeys.Add(keyIndex<0||reader.IsDBNull(keyIndex)?null:reader.GetString(keyIndex));
            result.Links.Add(linkIndex<0||reader.IsDBNull(linkIndex)?null:reader.GetString(linkIndex));
        }
        return result;
    }
}
