$(function(){
    var api=dental.finance.visit,l=abp.localization.getResource('Dental'),v,services=[],materials=[],staff=[],dirty=false,busy=false,id=new URLSearchParams(location.search).get('id');
    var edit=(abp.auth.isGranted('Dental.Visits.EditOpen')||abp.auth.isGranted('Dental.Visits.Complete')),correct=abp.auth.isGranted('Dental.Visits.EditClosed'),prices=abp.auth.isGranted('Dental.Catalog.PricesManage');
    function number(value,min,max,step){return $('<input class="form-control form-control-sm" type="number">').val(value).attr({min:min,max:max,step:step||1});}
    function load(){return api.get(id).then(function(data){v=data;if(edit||correct)return api.getStaff(v.branchId).then(function(rows){staff=rows;render(data);});render(data);});}
    function render(data){v=data;dirty=false;$('#VisitAssistant').empty().append($('<option>').val('').text('—'));staff.filter(function(e){return e.position===4;}).forEach(function(e){$('#VisitAssistant').append($('<option>').val(e.id).text(e.name));});$('#VisitAssistant').val(v.assistantId||'').prop('disabled',v.status!==0||!edit);var editable=(v.status===0&&edit)||(v.status===1&&correct);$('#VisitPatient').text(v.patientName);$('#VisitSummary').text(v.doctorName+' · '+dentalUi.dateTime(v.openedAt)+' · '+l('Finance:VisitStatus:'+v.status)+(v.approvalState?' · '+l('Finance:PendingApproval'):''));
        $('#VisitTotal').text(l('Finance:Total')+': '+dentalUi.money(v.total));$('#VisitPaid').text(l('Finance:Paid')+': '+dentalUi.money(v.paidTotal));$('#VisitDebt').text(l('Finance:Debt')+': '+dentalUi.money(v.debt));$('#VisitBalance').text(l('Finance:Balance')+': '+dentalUi.money(v.patientBalance));
        $('#VisitItems,#VisitMaterials').empty();v.items.forEach(function(i){itemRow(i,editable);});v.materials.forEach(function(m){materialRow(m,editable);});
        $('#VisitEditTools,#MaterialEditTools').toggleClass('d-none',!editable);$('#VisitSave,#MaterialsSave').toggle(v.status===0&&edit);$('#VisitClose').toggle(v.status===0&&abp.auth.isGranted('Dental.Visits.Complete'));$('#VisitCorrect').toggle(v.status===1&&correct);$('#VisitCancel').toggle(v.status!==2&&abp.auth.isGranted('Dental.Visits.Cancel'));$('#VisitPay').toggle(v.status!==2&&abp.auth.isGranted('Dental.Cash.PaymentCreate')).attr('href','/Cash?visitId='+v.id);}
    function itemRow(i,editable){var row=$('<tr>').data('item',i),qty=number(i.qty,1,100),price=number(i.unitPrice/100,0,null,.01),discount=number(i.discountPct,0,100,.01),teeth=$('<input class="form-control form-control-sm">').val((i.toothNumbers||[]).join(', '));
        qty.addClass('qty');price.addClass('price').prop('disabled',!prices&&v.status===0);discount.addClass('discount').prop('disabled',!abp.auth.isGranted('Dental.Catalog.DiscountsApply'));teeth.addClass('teeth');
        var doctor=$('<select class="form-select form-select-sm line-doctor">').prop('disabled',!editable||!abp.auth.isGranted('Dental.Visits.EditOpen'));
        var doctors=staff.filter(function(e){return e.position===3;});if(!doctors.length)doctors=[{id:i.doctorId,name:v.doctorName}];doctors.forEach(function(d){doctor.append($('<option>').val(d.id).text(d.name));});doctor.val(i.doctorId);
        row.append($('<td>').text(i.serviceName),$('<td>').append(doctor),$('<td>').append(qty),$('<td>').append(price),$('<td>').append(discount),$('<td>').append(teeth),$('<td>').append($('<button class="btn btn-sm btn-outline-danger">').text(l('Finance:Remove')).prop('disabled',!editable).on('click',function(){dirty=true;row.remove();})));if(!editable)row.find('input').prop('disabled',true);$('#VisitItems').append(row);}
    function materialRow(m,editable){var row=$('<tr>').data('material',m);row.append($('<td>').text(m.itemName),$('<td>').append(number(m.quantity,.000001,null,.000001).addClass('quantity').prop('disabled',!editable)),$('<td>').text(m.normQuantity),$('<td>').text(dentalUi.money(m.cost||0)),$('<td>').append($('<button class="btn btn-sm btn-outline-danger">').text(l('Finance:Remove')).prop('disabled',!editable).on('click',function(){row.remove();})));$('#VisitMaterials').append(row);}
    function lines(){return $('#VisitItems tr').map(function(){var r=$(this),i=r.data('item');return {serviceId:i.serviceId,doctorId:r.find('.line-doctor').val()||i.doctorId,qty:Number(r.find('.qty').val()),discountPct:Number(r.find('.discount').val()),unitPrice:(prices||v.status===1)?Math.round(Number(r.find('.price').val())*100):null,toothNumbers:r.find('.teeth').val().split(/[\s,]+/).filter(Boolean).map(Number)};}).get();}
    function usages(){return $('#VisitMaterials tr').map(function(){var r=$(this),m=r.data('material');return {itemId:m.itemId,quantity:Number(r.find('.quantity').val()),visitItemId:v.status===0?m.visitItemId:null};}).get();}
    function run(request){if(busy)return;busy=true;$('button').prop('disabled',true);request().then(render).always(function(){busy=false;$('button').prop('disabled',false);});}
    $('#VisitSave').on('click',function(){run(function(){return api.update(id,{concurrencyStamp:v.concurrencyStamp,items:lines(),assistantId:$('#VisitAssistant').val()||null});});});
    $('#MaterialsSave').on('click',function(){run(function(){return api.setMaterials(id,{concurrencyStamp:v.concurrencyStamp,materials:usages()});});});
    $('#VisitItems,#VisitMaterials,#VisitAssistant').on('input change',function(){dirty=true;});
    $('#VisitClose').on('click',function(){if(dirty){abp.message.warn(l('Finance:SaveFirst'));return;}abp.message.confirm(l('Finance:ConfirmCloseVisit')).then(function(ok){if(ok)run(function(){return api.close(id,{concurrencyStamp:v.concurrencyStamp});});});});
    $('#VisitCorrect').on('click',function(){var reason=$('#VisitReason').val().trim();if(!reason){abp.message.warn(l('Finance:ReasonRequired'));return;}run(function(){return api.correct(id,{concurrencyStamp:v.concurrencyStamp,items:lines(),materials:usages(),reason:reason});});});
    $('#VisitCancel').on('click',function(){var reason=$('#VisitReason').val().trim();if(!reason){abp.message.warn(l('Finance:ReasonRequired'));return;}abp.message.confirm(l('Finance:ConfirmCancelVisit')).then(function(ok){if(ok)run(function(){return api.cancel(id,{concurrencyStamp:v.concurrencyStamp,reason:reason});});});});
    $('#VisitAddService').on('click',function(){var s=services.find(function(s){return s.id===$('#VisitService').val();});if(s){dirty=true;itemRow({serviceId:s.id,serviceName:s.name,doctorId:v.doctorId,qty:1,unitPrice:s.price||0,discountPct:0,toothNumbers:[]},true);}});
    $('#VisitAddMaterial').on('click',function(){var m=materials.find(function(m){return m.id===$('#VisitMaterial').val();});if(m){dirty=true;materialRow({itemId:m.id,itemName:m.name,quantity:1,normQuantity:1,cost:0,visitItemId:null},true);}});
    load().then(function(){if(edit||correct)api.getServices(v.branchId).then(function(r){services=r;services.forEach(function(s){$('#VisitService').append($('<option>').val(s.id).text(s.name));});});});
    if(edit||correct)api.getMaterials().then(function(r){materials=r;materials.forEach(function(m){$('#VisitMaterial').append($('<option>').val(m.id).text(m.name));});});
});


