$(function () {
    'use strict';
    const api=dental.purchasing.purchasing, can=p=>abp.auth.isGranted('Dental.'+p), money=n=>(Number(n||0)/100).toLocaleString('ru-RU',{minimumFractionDigits:2});
    const rs=['Черновик','Отправлена','Обработана','Отклонена'], os=['Черновик','На подтверждении','Отправлен','Частично принят','Принят','Отменён'];
    const modal=new bootstrap.Modal(document.getElementById('PurchaseModal'));
    let warehouses=[],suppliers=[],items=[],submit;
    const error=e=>abp.message.error(e.message||(e.responseJSON&&e.responseJSON.error&&e.responseJSON.error.message)||'Не удалось выполнить действие.');
    const button=(label,action)=>$('<button type="button" class="btn btn-sm btn-outline-primary me-1">').text(label).on('click',()=>Promise.resolve().then(action).catch(error));
    function table(root,headers,rows) { const t=$('<table class="table">'),head=$('<tr>'),body=$('<tbody>'); headers.forEach(h=>head.append($('<th>').text(h))); rows.forEach(values=>{const row=$('<tr>'); values.forEach(v=>row.append($('<td>').append(v instanceof jQuery?v:document.createTextNode(v==null?'':String(v)))));body.append(row);}); $(root).empty().append(t.append($('<thead>').append(head),body)); }
    function open(title,action) { $('#PurchaseTitle').text(title);$('#PurchaseFields').empty();submit=action;modal.show(); }
    function input(id,label,type,value,required=true) { const f=$('<input class="form-control">').attr({id,type:type||'text'}).val(value==null?'':value).prop('required',required);if(type==='number')f.attr({min:0,step:'0.01'});$('#PurchaseFields').append($('<div class="mb-3">').append($('<label class="form-label">').attr('for',id).text(label),f));return f; }
    function select(id,label,rows) { const f=$('<select class="form-select mb-3">').attr('id',id);rows.forEach(r=>f.append($('<option>').val(r.id).text(r.name)));$('#PurchaseFields').append($('<label class="form-label">').attr('for',id).text(label),f);return f; }
    function lines(source,price) {
        const t=$('<table class="table">').append('<thead><tr><th>Товар</th><th>Количество</th>'+(price?'<th>Цена, ₸</th>':'')+'<th></th></tr></thead>'),body=$('<tbody id="PurchaseLines">');
        function add(l) { const row=$('<tr>'),item=$('<select class="form-select" required>').addClass('line-item');items.forEach(i=>item.append($('<option>').val(i.id).text(i.name))); if(l)item.val(l.itemId);const qty=$('<input type="number" min="0.000001" step="0.000001" class="form-control line-qty" required>').val(l?l.qty:1);row.append($('<td>').append(item),$('<td>').append(qty));if(price)row.append($('<td>').append($('<input type="number" min="0" step="0.01" class="form-control line-price" required>').val(l?l.unitPrice/100:0)));row.append($('<td>').append(button('Удалить',()=>row.remove())));body.append(row); }
        $('#PurchaseFields').append(t.append(body),button('Добавить товар',()=>add()));(source&&source.length?source:[null]).forEach(add);
    }
    function readLines() { return $('#PurchaseLines tr').map(function(){return {itemId:$(this).find('.line-item').val(),qty:Number($(this).find('.line-qty').val()),unitPrice:Math.round(Number($(this).find('.line-price').val()||0)*100)};}).get(); }
    async function load() {
        const values=await Promise.all([api.getWarehouses(),api.getSuppliers(),api.getItems(),api.getRequests(),api.getOrders(),api.getPrices()]);warehouses=values[0];suppliers=values[1];items=values[2];const requests=values[3],orders=values[4];
        const demand=new Map();requests.filter(r=>r.status===1).forEach(r=>r.lines.forEach(l=>{const old=demand.get(l.itemId)||{name:l.itemName,qty:0,warehouses:new Set()};old.qty+=l.qty-l.processedQty;old.warehouses.add(r.warehouseName);demand.set(l.itemId,old);}));table('#PurchaseDemand',['Товар','Осталось заказать','Склады'],Array.from(demand.values()).filter(d=>d.qty>0).map(d=>[d.name,d.qty,Array.from(d.warehouses).join(', ')]));
        table('#PurchaseRequests',['Склад','Источник','Статус','Товары','Действия'],requests.map(r=>{const a=$('<div>');if(r.status===0&&can('Purchase.RequestCreate'))a.append(button('Отправить',async()=>{await api.submit(r.id,{concurrencyStamp:r.concurrencyStamp});await load();}));if(r.status===1&&can('Purchase.OrderCreate'))a.append(button('Обработать',()=>process(r)),button('Отклонить',async()=>{if(await abp.message.confirm('Отклонить заявку?')){await api.process(r.id,{concurrencyStamp:r.concurrencyStamp,reject:true});await load();}}));return [r.warehouseName,r.source===0?'Авто':'Вручную',rs[r.status],r.lines.map(l=>l.itemName+': '+l.qty+' (обработано '+l.processedQty+')').join('; '),a];}));
        table('#PurchaseOrders',['Номер','Поставщик','Склад','Статус','Сумма, ₸','Товары','Действия'],orders.map(o=>{const a=$('<div>').append(button('Текст заказа',()=>{open('Заказ '+o.number,async()=>{});input('OrderText','Текст для поставщика','text',o.lines.map(l=>l.itemName+' — '+l.qty+' × '+money(l.unitPrice)+' ₸').join('; ')).prop('readonly',true);}));a.append($('<a class="btn btn-sm btn-outline-secondary me-1">').attr('href','/Purchasing?handler=Export&id='+encodeURIComponent(o.id)+'&format=xlsx').text('Excel'),$('<a class="btn btn-sm btn-outline-secondary me-1">').attr('href','/Purchasing?handler=Export&id='+encodeURIComponent(o.id)+'&format=pdf').text('PDF'));if(o.status===0&&can('Purchase.OrderCreate'))a.append(button('Изменить',()=>editOrder(o)));if(o.status===0&&can('Purchase.OrderCreate'))a.append(button('Отправлен поставщику',()=>{open('Зафиксировать отправку',async()=>{await api.send(o.id,{concurrencyStamp:o.concurrencyStamp,via:$('#Via').val()});await load();});input('Via','Канал отправки','text','Email');}));if([2,3].includes(o.status)&&can('Inventory.Receive'))a.append(button('Принять',()=>receive(o)));if([0,1,2].includes(o.status)&&o.lines.every(l=>l.receivedQty===0)&&can('Purchase.OrderCreate'))a.append(button('Отменить',async()=>{if(await abp.message.confirm('Отменить заказ?')){await api.cancel(o.id,{concurrencyStamp:o.concurrencyStamp});await load();}}));return [o.number,o.supplierName,o.warehouseName,os[o.status],money(o.total),o.lines.map(l=>l.itemName+': '+l.receivedQty+'/'+l.qty).join('; '),a];}));
        table('#PurchasePrices',['Товар','Поставщик','Цена, ₸','Обновлено'],values[5].map(p=>[p.itemName,p.supplierName,money(p.price),p.priceAt?new Date(p.priceAt).toLocaleDateString('ru-RU'):'—']));
        if(can('Purchase.OrderCreate')){const invoices=await api.getInvoices();table('#PurchaseInvoices',['Счёт','Поставщик','Дата','Срок','Сумма, ₸','Оплачено, ₸','Возвращено, ₸','Долг, ₸','Действия'],invoices.map(i=>{const a=$('<div>'),debt=i.amount-i.paidAmount-i.returnedAmount;if(debt>0)a.append(button('Оплата',()=>{const key=crypto.randomUUID();open('Оплата счёта '+i.number,async()=>{await api.payInvoice(i.id,{concurrencyStamp:i.concurrencyStamp,amount:Math.round(Number($('#PayAmount').val())*100),reference:$('#Reference').val(),idempotencyKey:key});await load();});input('PayAmount','Сумма, ₸','number',debt/100);input('Reference','Номер банковского подтверждения','text','');}));if(can('Inventory.Writeoff')&&i.returnedAmount<i.amount)a.append(button('Возврат',async()=>{const available=await api.getReturnLines(i.id);open('Возврат по счёту '+i.number,async()=>{await api.returnInvoice(i.id,{concurrencyStamp:i.concurrencyStamp,reason:$('#ReturnReason').val(),lines:readLines()});await load();});input('ReturnReason','Причина возврата','text','');lines(available,false);}));return [i.number,i.supplierName,i.date,i.dueDate,money(i.amount),money(i.paidAmount),money(i.returnedAmount),money(debt),a];}));}else $('#PurchaseInvoices,#PurchaseInvoiceNote').hide();
    }
    function editOrder(o) { open('Изменить '+o.number,async()=>{await api.updateOrder(o.id,{concurrencyStamp:o.concurrencyStamp,warehouseId:$('#Warehouse').val(),supplierId:$('#Supplier').val(),expectedAt:$('#Expected').val()?dentalCalendarDates.normalize($('#Expected').val()):null,comment:$('#Comment').val(),lines:readLines()});await load();});select('Warehouse','Склад',warehouses).val(o.warehouseId);select('Supplier','Поставщик',suppliers).val(o.supplierId);input('Expected','Ожидаемая дата','date',o.expectedAt||'',false);input('Comment','Комментарий','text',o.comment||'',false);lines(o.lines,true); }
    function process(r) { open('Обработка заявки',async()=>{await api.process(r.id,{concurrencyStamp:r.concurrencyStamp,supplierId:$('#Supplier').val()||null,sourceWarehouseId:$('#SourceWarehouse').val()||null,lines:readLines()});await load();});select('Supplier','Поставщик',[{id:'',name:'Не выбран'},...suppliers]);select('SourceWarehouse','Или переместить со склада',[{id:'',name:'Создать заказ'},...warehouses.filter(w=>w.id!==r.warehouseId)]);lines(r.lines.filter(l=>l.qty>l.processedQty).map(l=>({...l,qty:l.qty-l.processedQty})),true); }
    function receive(o) { open('Приёмка '+o.number,async()=>{const id=await api.receive(o.id,{concurrencyStamp:o.concurrencyStamp,invoiceNumber:$('#InvoiceNumber').val(),invoiceDate:dentalCalendarDates.normalize($('#InvoiceDate').val()),lines:readLines()});modal.hide();await load();abp.notify.success('Приход проведён, счёт создан.');});input('InvoiceNumber','Номер накладной','text','');input('InvoiceDate','Дата накладной','date',new Date().toISOString().slice(0,10));lines(o.lines.filter(l=>l.qty>l.receivedQty).map(l=>({...l,qty:l.qty-l.receivedQty})),false); }
    $('#PurchaseRequest').toggle(can('Purchase.RequestCreate')).on('click',()=>{open('Новая заявка',async()=>{await api.createRequest({warehouseId:$('#Warehouse').val(),comment:$('#Comment').val(),lines:readLines()});await load();});select('Warehouse','Склад',warehouses);input('Comment','Комментарий','text','',false);lines(null,false);});
    $('#PurchaseOrder').toggle(can('Purchase.OrderCreate')).on('click',()=>{open('Новый заказ',async()=>{await api.createOrder({warehouseId:$('#Warehouse').val(),supplierId:$('#Supplier').val(),expectedAt:$('#Expected').val()?dentalCalendarDates.normalize($('#Expected').val()):null,comment:$('#Comment').val(),lines:readLines()});await load();});select('Warehouse','Склад',warehouses);select('Supplier','Поставщик',suppliers);input('Expected','Ожидаемая дата','date','',false);input('Comment','Комментарий','text','',false);lines(null,true);});
    $('#PurchaseGenerate').toggle(can('Purchase.RequestCreate')).on('click',()=>api.generate().then(()=>load()).catch(error));$('#PurchaseReload').on('click',()=>load().catch(error));
    $('#PurchaseForm').on('submit',async e=>{e.preventDefault();const b=$('#PurchaseForm button[type=submit]').prop('disabled',true);try{await submit();modal.hide();}catch(ex){error(ex);}finally{b.prop('disabled',false);}});load().catch(error);
});
