$(function(){
    if(!$('#DashboardCards').length)return;
    var api=dental.dashboard.dashboard,l=abp.localization.getResource('Dental'),generation=0;
    function card(label,value,url){$('#DashboardCards').append($('<div class="col-6 col-lg-3">').append($('<a class="card h-100 text-decoration-none text-body">').attr('href',url).append($('<div class="card-body">').append($('<div class="text-muted mb-2">').text(l(label)),$('<div class="fs-3 fw-semibold">').text(value)))));}
    function render(r){$('#DashboardDate').val(r.date);$('#DashboardCards,#DashboardAttention,#DashboardBranches').empty();card('Dashboard:Appointments',r.appointments,'/Schedule');card('Dashboard:Unconfirmed',r.unconfirmed,'/Schedule');card('Dashboard:Completed',r.completed,'/Visits');card('Dashboard:Utilization',r.utilizationPct==null?'—':r.utilizationPct+'%','/Schedule');
        if(r.canSeeFinance){card('Dashboard:ReceivedDay',dentalUi.money(r.receivedToday),'/Cash');card('Dashboard:RevenueWeek',dentalUi.money(r.revenueWeek),'/Visits');card('Finance:Debt',dentalUi.money(r.debt),'/Patients');}
        [['Dashboard:Unconfirmed',r.unconfirmed,'/Schedule'],['Dashboard:PendingApprovals',r.pendingApprovals,'/Approvals'],['Dashboard:LowStock',r.lowStock,'/Inventory'],['Dashboard:Expiring',r.expiringBatches,'/Inventory'],['Dashboard:OverdueShifts',r.overdueShifts,'/Cash']].forEach(function(item){if(item[1])$('#DashboardAttention').append($('<a class="btn btn-outline-warning">').attr('href',item[2]).text(l(item[0])+': '+item[1]));});if(!$('#DashboardAttention').children().length)$('#DashboardAttention').text(l('Dashboard:NoAttention'));
        $('.dashboard-finance').toggle(r.canSeeFinance);r.branches.forEach(function(b){var row=$('<tr>').append($('<td>').text(b.name),$('<td>').text(b.appointments),$('<td>').text(b.unconfirmed));if(r.canSeeFinance)row.append($('<td>').text(dentalUi.money(b.revenueToday)),$('<td>').text(dentalUi.money(b.debt)));$('#DashboardBranches').append(row);});}
    function load(){var n=++generation;$('#DashboardRefresh').prop('disabled',true);api.get({branchId:$('#DashboardBranch').val()||null,date:$('#DashboardDate').val()?dentalCalendarDates.normalize($('#DashboardDate').val()):null}).then(function(r){if(n===generation)render(r);}).always(function(){if(n===generation)$('#DashboardRefresh').prop('disabled',false);});}
    dental.branches.branch.getLookup().then(function(r){$('#DashboardBranch').append($('<option>').val('').text(l('AllBranches')));r.items.forEach(function(b){$('#DashboardBranch').append($('<option>').val(b.id).text(b.name));});load();});$('#DashboardBranch,#DashboardDate').on('change',load);$('#DashboardRefresh').on('click',load);
});
